version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - node1:node1
      - node2:node2
    ports:
      - "8000:80"

  node1:
    image: ddubs/vulpix-node-example
    # build: ./node
    ports:
      - "8001:8080"
    
  node2:
    image: ddubs/vulpix-node-example
    # build: ./node
    ports:
      - "8002:8080"