version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - node1:node1
      - node2:node2
    ports:
      - "8000:80"

  node1:
    image: ddubs/vulpix-node-example
    # build: ./node
    ports:
      - "8001:8080"
    
  node2:
    image: ddubs/vulpix-node-example
    # build: ./node
    ports:
      - "8002:8080"

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "9500:8080"
    container_name: cadvisor